python datasets/test.py --pred_dir data/spinnerf_dataset_sam/1/masks --target_dir data/spinnerf_dataset/1/images_4/label --mode mask
python datasets/test.py --pred_dir data/spinnerf_dataset_sam/2/masks --target_dir data/spinnerf_dataset/2/images_4/label --mode mask
python datasets/test.py --pred_dir data/spinnerf_dataset_sam/3/masks --target_dir data/spinnerf_dataset/3/images_4/label --mode mask
python datasets/test.py --pred_dir data/spinnerf_dataset_sam/4/masks --target_dir data/spinnerf_dataset/4/images_4/label --mode mask
python datasets/test.py --pred_dir data/spinnerf_dataset_sam/7/masks --target_dir data/spinnerf_dataset/7/images_4/label --mode mask
python datasets/test.py --pred_dir data/spinnerf_dataset_sam/9/masks --target_dir data/spinnerf_dataset/9/images_4/label --mode mask
python datasets/test.py --pred_dir data/spinnerf_dataset_sam/10/masks --target_dir data/spinnerf_dataset/10/images_4/label --mode mask
python datasets/test.py --pred_dir data/spinnerf_dataset_sam/12/masks --target_dir data/spinnerf_dataset/12/images_4/label --mode mask
python datasets/test.py --pred_dir data/spinnerf_dataset_sam/book/masks --target_dir data/spinnerf_dataset/book/images_4/label --mode mask
python datasets/test.py --pred_dir data/spinnerf_dataset_sam/trash/masks --target_dir data/spinnerf_dataset/trash/images_4/label --mode mask
